/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Report {
  'id' : ReportId,
  'submittedAt' : Time,
  'description' : string,
  'reportType' : string,
  'location' : [] | [string],
}
export type ReportId = bigint;
export type Time = bigint;
export interface Member {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'joinedAt' : bigint,
}
export interface Subscriber {
  'id' : bigint,
  'email' : string,
  'subscribedAt' : bigint,
}
export interface _SERVICE {
  'getAllReports' : ActorMethod<[], Array<Report>>,
  'submitReport' : ActorMethod<[string, string, [] | [string]], ReportId>,
  'joinClub' : ActorMethod<[string, string], bigint>,
  'subscribe' : ActorMethod<[string], bigint>,
  'getMembers' : ActorMethod<[], Array<Member>>,
  'getSubscribers' : ActorMethod<[], Array<Subscriber>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
