/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReportId = IDL.Nat;
export const Time = IDL.Int;
export const Report = IDL.Record({
  'id' : ReportId,
  'submittedAt' : Time,
  'description' : IDL.Text,
  'reportType' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
});
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'joinedAt' : IDL.Int,
});
export const Subscriber = IDL.Record({
  'id' : IDL.Nat,
  'email' : IDL.Text,
  'subscribedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], []),
  'submitReport' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [ReportId],
      [],
    ),
  'joinClub' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'subscribe' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReportId = IDL.Nat;
  const Time = IDL.Int;
  const Report = IDL.Record({
    'id' : ReportId,
    'submittedAt' : Time,
    'description' : IDL.Text,
    'reportType' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
  });
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'joinedAt' : IDL.Int,
  });
  const Subscriber = IDL.Record({
    'id' : IDL.Nat,
    'email' : IDL.Text,
    'subscribedAt' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], []),
    'submitReport' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [ReportId],
        [],
      ),
    'joinClub' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'subscribe' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
